<pre class="metadata">
Title: Subresource Integrity
Status: ED
ED: https://w3c.github.io/webappsec-subresource-integrity/
TR: http://www.w3.org/TR/sri-2/
Shortname: sri
Level: 2
Editor: Frederik Braun 68466, Mozilla, https://frederik-braun.com, fbraun@mozilla.com
Former Editor: Devdatta Akhawe, Dropbox Inc., http://devd.me, dev.akhawe@gmail.com
Former Editor: François Marier, Mozilla, https://fmarier.org, francois@mozilla.com
Former Editor: Joel Weinberger, Google Inc., https://joelweinberger.us, jww@google.com
Abstract:
  This specification defines a mechanism by which user agents may verify that a
  fetched resource has been delivered without unexpected manipulation.
Group: webappsec
Repository: w3c/webappsec-subresource-integrity
Indent: 2
Version History: https://github.com/w3c/webappsec-subresource-integrity/commits/gh-pages
WPT Path Prefix: /subresource-integrity/
WPT Display: closed

Markup Shorthands: css off, markdown on, http on
Ignored Vars: src, resource, val
</pre>

<pre class="anchors">
spec: ABNF; urlPrefix: https://tools.ietf.org/html/rfc5234
  type: dfn
    text: VCHAR; url: appendix-B.1
    text: WSP; url: appendix-B.1
  type: grammar
    text: VCHAR; url: appendix-B.1
    text: WSP; url: appendix-B.1

spec: RFC7234; urlPrefix: https://tools.ietf.org/html/rfc7234
  type: dfn
    text: Cache-Control; url: section-5.2
    text: no-transform; url: section-5.2.1.6

spec: SHA2; urlPrefix: https://csrc.nist.gov/publications/fips/fips180-4/fips-180-4.pdf
  type: dfn
    text: SHA-1; url: #
    text: SHA-2; url: #
    text: SHA-256; url: #
    text: SHA-384; url: #
    text: SHA-512; url: #

spec: RFC8288; urlPrefix: https://tools.ietf.org/html/rfc8288
  type: http-header
    text: link

spec: RFC9651; urlPrefix: https://tools.ietf.org/html/rfc9651
  type: dfn
    text: Dictionary; url: name-dictionaries
    text: inner list; url: name-inner-lists
    text: token; url: name-tokens

</pre>
<pre class="link-defaults">
spec:csp3; type:grammar; text:base64-value
</pre>

<pre class="biblio">
{
  "SHA2": {
    "href": "http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf",
    "title": "FIPS PUB 180-4, Secure Hash Standard"
  }
}
</pre>

  <!-- ####################################################################### -->

  # Introduction # {#intro}

  Sites and applications on the web are rarely composed of resources from
  only a single origin. For example, authors pull scripts and styles from a
  wide variety of services and content delivery networks, and must trust
  that the delivered representation is, in fact, what they expected to
  load. If an attacker can trick a user into downloading content from
  a hostile server (via DNS [[RFC1035]] poisoning, or other such means), the author has
  no recourse. Likewise, an attacker who can replace the file on the Content
  Delivery Network (CDN) server has the ability to inject arbitrary content.

  Delivering resources over a secure channel mitigates some of this risk: with
  TLS [[TLS]], HSTS [[RFC6797]], and pinned public keys
  [[RFC7469]], a user agent can be fairly certain
  that it is indeed speaking with the server it believes it's talking to. These
  mechanisms, however, authenticate <em>only</em> the server, <em>not</em> the content. An
  attacker (or administrator) with access to the server can manipulate content with
  impunity. Ideally, authors would not only be able to pin the keys of a
  server, but also pin the <em>content</em>, ensuring that an exact representation of
  a resource, and <em>only</em> that representation, loads and executes.

  This document specifies such a validation scheme, extending two HTML elements
  with an `integrity` attribute that contains a cryptographic hash
  of the representation of the resource the author expects to load. For instance,
  an author may wish to load some framework from a shared server rather than hosting it
  on their own origin. Specifying that the <em>expected</em> SHA-384 hash of
  `https://example.com/example-framework.js`
  is `Li9vy3DqF8tnTXuiaAJuML3ky+er10rcgNR/VqsVpcw+ThHmYcwiB1pbOxEbzJr7` means
  that the user agent can verify that the data it loads from that URL matches
  that expected hash before executing the JavaScript it contains. This
  integrity verification significantly reduces the risk that an attacker can
  substitute malicious content.

  This example can be communicated to a user agent by adding the hash to a
  `script` element, like so:

  <div class="example">
  <xmp highlight="html">
    <script src="https://example.com/example-framework.js"
            integrity="sha384-Li9vy3DqF8tnTXuiaAJuML3ky+er10rcgNR/VqsVpcw+ThHmYcwiB1pbOxEbzJr7"
            crossorigin="anonymous"></script>
  </xmp>
  </div>

  Scripts, of course, are not the only response type which would benefit
  from integrity validation. The scheme specified here also applies to `link`
  and future versions of this specification are likely to expand this coverage.

  <wpt>
    subresource-integrity.html
  </wpt>

  ## Goals ## {#goals}

  1.  Compromise of a third-party service should not automatically mean
      compromise of every site which includes its scripts. Content authors
      will have a mechanism by which they can specify expectations for
      content they load, meaning for example that they could load a
      <em>specific</em> script, and not <em>any</em> script that happens to have a
      particular URL.

  2.  The verification mechanism should have error-reporting functionality which
      would inform the author that an invalid response was received.

  ## Use Cases/Examples ## {#examples}

  ### Resource Integrity ### {#resource-integrity}

  *   An author wishes to use a content delivery network to improve performance
      for globally-distributed users. It is important, however, to ensure that
      the CDN's servers deliver <em>only</em> the code the author expects them to
      deliver. To mitigate the risk that a CDN compromise (or unexpectedly malicious
      behavior) would change that site in unfortunate ways, the following
      <a>integrity metadata</a> is added to the `link` element included on the page:

      <div class="example">
      <xmp highlight="html">
          <link rel="stylesheet" href="https://site53.example.net/style.css"
                integrity="sha384-+/M6kredJcxdsqkczBUjMLvqyHb1K/JThDXWsBVxMEeZHEaMKEOEct339VItX1zB"
                crossorigin="anonymous">
      </xmp>
      </div>

  *   An author wants to include JavaScript provided by a third-party
      analytics service. To ensure that only the code that has been carefully
      reviewed is executed, the author generates <a>integrity metadata</a> for
      the script, and adds it to the `script` element:

      <div class="example">
      <xmp highlight="html">
          <script src="https://analytics-r-us.example.com/v1.0/include.js"
                  integrity="sha384-MBO5IDfYaE6c6Aao94oZrIOiC6CGiSN2n4QUbHNPhzk5Xhm0djZLQqTpL0HzTUxk"
                  crossorigin="anonymous"></script>
      </xmp>
      </div>

  *   A user agent wishes to ensure that JavaScript code running in high-privilege HTML
      contexts (for example, a browser's New Tab page) aren't manipulated before display.
      <a>Integrity metadata</a> mitigates the risk that altered JavaScript will run
      in these pages' high-privilege contexts.

  <!-- ####################################################################### -->

  # Key Concepts and Terminology # {#terms}

  This section defines several terms used throughout the document.

  The term <dfn>digest</dfn> refers to the base64 encoded result of
  executing a cryptographic hash function on an arbitrary block of data.

  The terms [=/origin=] and [=same origin=] are defined in HTML. [[!HTML]]

  A <dfn>base64 encoding</dfn> is defined in <a
  href="https://tools.ietf.org/html/rfc4648#section-4">Section 4 of RFC 4648</a>.
  [[!RFC4648]]

  The <a>SHA-256</a>, <a>SHA-384</a>, and <a>SHA-512</a> are part
  of the <a>SHA-2</a> set of cryptographic hash functions defined by the
  NIST. [[!SHA2]]

  The <dfn>valid SRI hash algorithm token set</dfn> is the [=ordered set=]
  « "`sha256`", "`sha384`", "`sha512`" » (corresponding to [=SHA-256=],
  [=SHA-384=], and [=SHA-512=] respectively). The ordering of this set is
  meaningful, with stronger algorithms appearing later in the set. See
  [[#priority]] and [[#get-the-strongest-metadata]] for
  additional information.

  A string is a <dfn>valid SRI hash algorithm token</dfn> if its
  [=ASCII lowercase=] is [=set/contained=] in the
  [=valid SRI hash algorithm token set=].

  ## Grammatical Concepts ## {#grammar-concepts}

  The Augmented Backus-Naur Form (ABNF) notation used in this document is
  specified in RFC5234. [[!ABNF]]

  <a href="https://tools.ietf.org/html/rfc5234#appendix-B.1">Appendix B.1</a> of
  [[!ABNF]] defines the <a>VCHAR</a> (printing characters) and <a>WSP</a>
  (whitespace) rules.

  Content Security Policy defines the <a grammar>`base64-value`</a> and
  <a grammar>`hash-algorithm`</a> rules. [[!CSP]]

  <!-- ####################################################################### -->

  # Framework # {#framework}

  The integrity verification mechanism specified here boils down to the
  process of generating a sufficiently strong cryptographic digest for a
  resource, and transmitting that digest to a user agent so that it may be
  used to verify the response.

  ## Integrity metadata ## {#integrity-metadata-description}

  To verify the integrity of a response, a user agent requires <dfn>integrity
  metadata</dfn> as part of the <a for=/>request</a>. This metadata consists of
  the following pieces of information:

  * cryptographic hash function ("alg")
  * <a>digest</a> ("val")
  * options ("opt")

  The hash function and digest MUST be provided in order to validate a
  response's integrity.

  Note: At the moment, no options are defined. However, future versions of
  the spec may define options, such as MIME types [[!MIME-TYPES]].

  This metadata MUST be encoded in the same format as the `hash-source` (without
  the single quotes) in <a
  href="http://www.w3.org/TR/CSP2/#source-list-syntax">section 4.2 of the Content
  Security Policy Level 2 specification</a>.

  For example, given a script resource containing only the string `alert('Hello,
  world.');`, an author might choose <a>SHA-384</a> as a hash function.
  `H8BRh8j48O9oYatfu5AZzq6A9RINhZO5H16dQZngK7T62em8MUt1FLm52t+eX6xO` is the <a
  lt="base64 encoding">base64 encoded</a> digest that results. This can be encoded
  as follows:

  <div class="example">
  <xmp>
      sha384-H8BRh8j48O9oYatfu5AZzq6A9RINhZO5H16dQZngK7T62em8MUt1FLm52t+eX6xO
  </xmp>
  </div>

  <div class="note">
  Digests may be generated using any number of utilities. <a
  href="https://www.openssl.org/">OpenSSL</a>, for example, is quite commonly
  available. The example in this section is the result of the following command
  line:

  <xmp highlight="shell">
      echo -n "alert('Hello, world.');" | openssl dgst -sha384 -binary | openssl base64 -A
  </xmp>
  </div>

  ## Cryptographic hash functions ## {#hash-functions}

  Conformant user agents MUST support the <a>SHA-256</a>, <a>SHA-384</a>,
  and <a>SHA-512</a> cryptographic hash functions for use as part of a
  request's <a>integrity metadata</a> and MAY support additional hash functions
  defined in future iterations of this document.

  NOTE: The algorithms supported in this document are (currently!) believed to be
  resistent to second-preimage and collision attacks. Future additions/removals
  from the set of supported algorithms would be well-advised to apply similar
  standard. See [[#hash-collision-attacks]].

  ### Agility ### {#agility}

  Multiple sets of <a>integrity metadata</a> may be associated with a single
  resource in order to provide agility in the face of future cryptographic discoveries.
  For example, the resource described in the previous section may be described
  by either of the following hash expressions:

  <div class="example">
  <xmp>
      sha384-H8BRh8j48O9oYatfu5AZzq6A9RINhZO5H16dQZngK7T62em8MUt1FLm52t+eX6xO
      sha512-Q2bFTOhEALkN8hOms2FKTDLy7eugP2zFZ1T8LCvX42Fp3WoNr3bjZSAHeOsHrbV1Fu9/A0EzCinRE7Af1ofPrw==
  </xmp>
  </div>

  Authors may choose to specify both, for example:

  <div class="example">
  <xmp highlight="html">
      <script src="hello_world.js"
         integrity="sha384-H8BRh8j48O9oYatfu5AZzq6A9RINhZO5H16dQZngK7T62em8MUt1FLm52t+eX6xO
                    sha512-Q2bFTOhEALkN8hOms2FKTDLy7eugP2zFZ1T8LCvX42Fp3WoNr3bjZSAHeOsHrbV1Fu9/A0EzCinRE7Af1ofPrw=="
         crossorigin="anonymous"></script>
  </xmp>
  </div>

  In this case, the user agent will choose the strongest hash function in the
  list, and use that metadata to validate the response (as described below in
  the [[#parse-metadata-section]] and [[#get-the-strongest-metadata]] algorithms).

  When a hash function is determined to be insecure, user agents SHOULD deprecate
  and eventually remove support for integrity validation using the insecure hash
  function. User agents MAY check the validity of responses using a digest based on
  a deprecated function.

  To allow authors to switch to stronger hash functions without being held back by older
  user agents, validation using unsupported hash functions acts like no integrity value
  was provided (see the [[#does-response-match-metadatalist]] algorithm below).
  Authors  are encouraged to use strong hash functions, and to begin migrating to
  stronger hash functions as they become available.

  ### Priority ### {#priority}

  The prioritization of hash algorithms is specified via the ordering of their
  respective tokens in the [=valid SRI hash algorithm token set=]. Algorithms
  appearing earlier in that set are weaker than algorithms appearing later in
  that set.

  As currently specified, [=SHA-256=] is weaker than [=SHA-384=], which is in
  turn weaker than [=SHA-512=]. No other hashing algorithms are currently
  supported by this specification.


  ## Response verification algorithms ## {#verification-algorithms}

  ### Apply |algorithm| to |bytes| ### {#apply-algorithm-to-response}

  1.  Let |result| be the result of applying |algorithm| to |bytes|.
  2.  Return the result of <a>base64 encoding</a> |result|.

  ### Parse metadata ### {#parse-metadata-section}

  When asked to <dfn export>parse metadata</dfn> given a string |metadata|, run the
  following steps:

  Note: the algorithm returns a set of hash expressions whose hash functions are understood
  by the user agent.

  1.  Let |result| be the empty set.
  2.  For each |item| returned by <a lt="strictly split">splitting</a>
      |metadata| on spaces:
      1.  Let |expression-and-options| be the result of
          <a lt="strictly split">splitting</a> |item| on U+003F (?).
      2.  Let |algorithm-expression| be |expression-and-options|[0].
      3.  Let |base64-value| be the empty string.
      4.  Let |algorithm-and-value| be the result of
          splitting |algorithm-expression| on the first occurence of U+002D (-).
      5.  Let |algorithm| be |algorithm-and-value|[0].
      6.  If |algorithm| is not a [=valid SRI hash algorithm token=], then
          [=iteration/continue=].
      7.  If |algorithm-and-value|[1] <a for=list>exists</a>, set
          |base64-value| to |algorithm-and-value|[1].
      8.  Let |metadata| be the ordered map  «["alg" → |algorithm|,
          "val" → |base64-value|]».

         Note: Since no `options` are defined (see the
         [[#integrity-metadata-description]]), a corresponding entry is not set
         in |metadata|. If `options` are defined in a future version,
         |expression-and-options|[1] can be utilized as `options`.

      9. <a for=list>Append</a> |metadata| to |result|.
  3.  Return |result|.

  ### Get the strongest metadata from |set| ### {#get-the-strongest-metadata}

  1.  Let |result| be the empty set and |strongest| be null.
  2.  For each |item| in |set|:
      1.  Assert: |item|["`alg`"] is a [=valid SRI hash algorithm token=].
      2.  If |result| is the empty set, then:
          1. [=set/Append=] |item| to |result|.
          2. Set |strongest| to |item|.
          3. [=iteration/Continue=].
      3.  Let |currentAlgorithm| be |strongest|["`alg`"], and |currentAlgorithmIndex|
          be the index of |currentAlgorithm| in the [=valid SRI hash algorithm token set=].
      4.  Let |newAlgorithm| be the |item|["`alg`"], and |newAlgorithmIndex|
          be the index of |newAlgorithm| in the [=valid SRI hash algorithm token set=].
      5.  If |newAlgorithmIndex| is less than |currentAlgorithmIndex|, [=iteration/continue=].
      6.  Otherwise, if |newAlgorithmIndex| is greater than |currentAlgorithmIndex|:
          1.  Set |strongest| to |item|.
          2.  Set |result| to « |item| ».
      7.  Otherwise, |newAlgorithmIndex| and |currentAlgorithmIndex| are the
          same value. [=set/Append=] |item| to |result|.
  3.  Return |result|.

<h4 dfn export id=does-response-match-metadatalist>Do |bytes| match |metadataList|?</h4>

  1.  Let |parsedMetadata| be the result of
      <a lt="parse metadata">parsing |metadataList|</a>.
  2.  If |parsedMetadata| [=set/is empty=] set, return `true`.
  3.  Let |metadata| be the result of <a href="#get-the-strongest-metadata">
      getting the strongest metadata from |parsedMetadata|</a>.
  4.  For each |item| in |metadata|:
      1.  Let |algorithm| be the |item|["alg"].
      2.  Let |expectedValue| be the |item|["val"].
      3.  Let |actualValue| be the result of <a
          href="#apply-algorithm-to-response">applying |algorithm| to |bytes|
          </a>.
      4.  If |actualValue| is a case-sensitive match for
          |expectedValue|, return `true`.
  5.  Return `false`.

  This algorithm allows the user agent to accept multiple, valid strong hash
  functions. For example, a developer might write a `script` element such as:

  <div class="example">
  <xmp highlight="html">
      <script src="https://example.com/example-framework.js"
              integrity="sha384-Li9vy3DqF8tnTXuiaAJuML3ky+er10rcgNR/VqsVpcw+ThHmYcwiB1pbOxEbzJr7
                         sha384-+/M6kredJcxdsqkczBUjMLvqyHb1K/JThDXWsBVxMEeZHEaMKEOEct339VItX1zB"
              crossorigin="anonymous"></script>
  </xmp>
  </div>

  which would allow the user agent to accept two different content payloads, one
  of which matches the first <a>SHA-384</a> hash value and the other matches the second
  <a>SHA-384</a> hash value.

  Note: User agents may allow users to modify the result of this algorithm via
  user preferences, bookmarklets, third-party additions to the user agent, and
  other such mechanisms. For example, redirects generated by an extension like <a
  href="https://www.eff.org/https-everywhere">HTTPS Everywhere</a> could load and
  execute correctly, even if the HTTPS version of a resource differs from the HTTP
  version.

  Note: Subresource Integrity requires CORS and it is a logical error
  to attempt to use it without CORS. User agents are encouraged to report a
  warning message to the developer console to explain this failure. [[!Fetch]]

  ## Verification of HTML document subresources ## {#verification-of-html-document-subresources}

  A variety of HTML elements result in requests for resources that are to be
  embedded into the document, or executed in its context. To support integrity
  metadata for some of these elements, a new `integrity` attribute is added to
  the list of content attributes for the `link` and `script` elements. [[!HTML]]

  Note: A future revision of this specification is likely to include integrity support
  for all possible subresources, i.e., `a`, `audio`, `embed`, `iframe`, `img`,
  `link`, `object`, `script`, `source`, `track`, and `video` elements.

  ## The `integrity` attribute ## {#the-integrity-attribute}

  The `integrity` attribute represents <a>integrity metadata</a> for an element.
  The value of the attribute MUST be either the empty string, or at least one
  valid metadata as described by the following ABNF grammar:

  <pre dfn-type="grammar" link-type="grammar">
      <dfn>integrity-metadata</dfn> = *<a>WSP</a> <a>hash-with-options</a> *(1*<a>WSP</a> <a>hash-with-options</a> ) *<a>WSP</a> / *<a>WSP</a>
      <dfn>hash-with-options</dfn>  = <a>hash-expression</a> *("?" <a>option-expression</a>)
      <dfn>option-expression</dfn>  = *<a>VCHAR</a>
      <dfn>hash-expression</dfn>    = <a grammar>hash-algorithm</a> "-" <a grammar>base64-value</a>
  </pre>

  `option-expression`s are associated on a per `hash-expression` basis and are
  applied only to the `hash-expression` that immediately precedes it.

  In order for user agents to remain fully forwards compatible with future
  options, the user agent MUST ignore all unrecognized  `option-expression`s.

  Note: Note that while the `option-expression` has been reserved in the syntax,
  no options have been defined. It is likely that a future version of the spec
  will define a more specific syntax for options, so it is defined here as broadly
  as possible.

  ## The `integrity` link processing option ## {#the-integrity-link-processing-option}

  <a>Integrity metadata</a> can also be specified for [:link:] HTTP response headers
  as an `integrity` link parameter which MUST be specified using the same
  <a grammar>`integrity-metadata`</a> grammar that applies to `integrity` attributes
  on elements. For example:

  ```http
  Link: </style.css>; rel=preload; as=style;  crossorigin="anonymous"; integrity="sha256-[digest goes here]"
  ```
  

  ## Handling integrity violations ## {#handling-integrity-violations}

  The user agent will refuse to render or execute responses that fail an integrity
  check, instead returning a network error as defined in Fetch [[!Fetch]].

  Note: On a failed integrity check, an `error` event is fired. Developers
  wishing to provide a canonical fallback resource (e.g., a resource not served
  from a CDN, perhaps from a secondary, trusted, but slower source) can catch this
  `error` event and provide an appropriate handler to replace the
  failed resource with a different one.

  <!-- ####################################################################### -->
  
  ## Integrity-Policy ## {#integrity-policy-section}
  The `Integrity-Policy` and `Integrity-Policy-Report-Only` HTTP headers enable a document to
  enforce a policy regarding the integrity metadata requirements on all the subresources it
  loads of certain <a for=request>destinations</a>.

  The headers' value is a <a>Dictionary</a> [[RFC9651]], with every member-value being an
  <a>inner list</a> of <a>tokens</a>.
  
  A <dfn>source</dfn> is a string. The only possible value for it is "`inline`".

  A <dfn>destination</dfn> is a <a>destination type</a>. The possible values for it are
  "`script`" and "`style`".

  An <dfn export>integrity policy</dfn>, is a <a>struct</a> that contains the following:

    * <dfn>sources</dfn>, a list of <a>source</a>s, initially empty.
    * <dfn>blocked destinations</dfn>, a list of <a>destination</a>s, initially empty.
    * <dfn>endpoints</dfn>, a <a for=/>list</a> of strings, initially empty.

  When <dfn>processing an integrity policy</dfn>, with a <a for=/>header list</a> |headers|
  and a <a>header name</a> |headerName|, do the following:

  1. Let |integrityPolicy| be a new <a for=/>integrity policy</a>.
  1. Let |dictionary| be the result of <a>getting a structured field value</a> from |headers|
     given |headerName| and "`dictionary`".
  1. If |dictionary|["`sources`"] does not <a for=list>exist</a> or if its value
     <a for=list>contains</a> "`inline`", <a for=list>append</a> "`inline`" to
     |integrityPolicy|'s <a>sources</a>.
  1. If |dictionary|["`blocked-destinations`"] <a for=list>exists</a>:
    1. If its value <a for=list>contains</a> "`script`",
       <a for=list>append</a> "`script`" to |integrityPolicy|'s <a>blocked destinations</a>.
    1. If its value <a for=list>contains</a> "`style`",
       <a for=list>append</a> "`style`" to |integrityPolicy|'s <a>blocked destinations</a>.
  1. If |dictionary|["`endpoints`"] <a for=map>exists</a>:
    1. Set |integrityPolicy|'s <a>endpoints</a> to |dictionary|['endpoints'].
  1. Return |integrityPolicy|.

  <div class=example>
  The following header block the request for any external script that's loaded without integrity
  metadata (or any no-CORS external script).
  ```http
    Integrity-Policy: blocked-destinations=(script), endpoints=(integrity-endpoint)
  ```
  The blocking will also trigger a report to the "`integrity-endpoint`"
  reporting endpoint (defined by the relevant `Reporting-Endpoints` header).
  
  Developers can also register a ReportingObserver for "`integrity-violation`" to get JavaScript-based
  reports.
  </div>
  
  ### Parse Integrity-Policy headers ### {#parse-integrity-policy-headers-section}
  To <dfn export>parse Integrity-Policy headers</dfn>, given a <a for=/>Response</a> |response|
  and a <a for=/>policy container</a> |container|, do the following:

  1. Let |headers| be |response|'s <a for=response>header list</a>.
  1. If |headers| <a for="header list">contains</a> ``integrity-policy``,
     set |container|'s <a for="policy container">integrity policy</a> be the result of running
     <a>processing an integrity policy</a> with the corresponding <a>header value</a>.
  1. If |headers| <a for="header list">contains</a> ``integrity-policy-report-only``,
     set |container|'s <a>report only integrity policy</a> be the result of running
     <a>processing an integrity policy</a> with the corresponding <a>header value</a>.
  
  ### Should request be blocked by Integrity Policy ### {#should-request-be-blocked-by-integrity-policy-section}
  To determine <dfn export>should request be blocked by integrity policy</dfn>, given a <a for=/>request</a> |request|,
  do the following:

  1. Let |policyContainer| be |request|'s <a for=request>policy container</a>.
  1. Let |parsedMetadata| be the result of calling <a>parse metadata</a> with 
     |request|'s <a for=request>integrity metadata</a>.
  1. If |parsedMetadata| is not the empty set and
     |request|'s <a for=request>mode</a> is either "`cors`" or "`same-origin`",
     return "Allowed".
  1. If |request|'s <a for=request>url</a> is <a lt="is local">local</a>,
     return "Allowed".
  1. Let |policy| be |policyContainer|'s <a for="policy container">integrity policy</a>.
  1. Let |reportPolicy| be |policyContainer|'s <a>report only integrity policy</a>.
  1. If both |policy| and |reportPolicy| are empty <a for=/>integrity policy</a>s, return "Allowed".
  1. Let |global| be |request|'s <a for=request>client</a>'s <a for="environment settings object">global object</a>.
  1. If |global| is not a {{Window}} nor a {{WorkerGlobalScope}}, return "`Allowed`".
  1. Let |block| be a boolean, initially false.
  1. Let |reportBlock| be a boolean, initially false.
  1. If |policy|'s <a>sources</a> <a for=list>contains</a> "`inline`"
     and |policy|'s <a>blocked destinations</a> <a for=list>contains</a>
     |request|'s <a for=request>destination</a>,
     set |block| to true.
  1. If |reportPolicy|'s <a>sources</a> <a for=list>contains</a> "`inline`"
     and |reportPolicy|'s <a>blocked destinations</a> <a for=list>contains</a>
     |request|'s <a for=request>destination</a>,
     set |reportBlock| to true.
  1. If |block| is true or |reportBlock| is true, then <a>report violation</a>
     with |request|, |block|, |reportBlock|, |policy| and |reportPolicy|.
  1. If |block| is true, then return "`Blocked`"; otherwise "`Allowed`".
 
  ### Report violations ### {#report-violations}

  <pre class="idl">
    dictionary IntegrityViolationReportBody : ReportBody {
      USVString documentURL;
      USVString blockedURL;
      USVString destination;
      boolean   reportOnly;
    };
  </pre>

  To <dfn>report violation</dfn> given a <a for=/>Request</a> |request|, a boolean |block|,
  a boolean |reportBlock|, an <a for=/>integrity policy</a> |policy|,
  and an <a for=/>integrity policy</a> |reportPolicy|, do the following:

  1. <a>Assert</a>: |request|'s <a for=request>client</a> is not null.
  1. Let |settingsObject| be |request|'s <a for=request>client</a>.
  1. Let |global| be |settingsObject|'s <a for="environment settings object">global object</a>.
  1. <a>Assert</a>: |global| is a {{Window}} or a {{WorkerGlobalScope}}.
  1. Let |url| be null.
  1. If |global| is a {{Window}}, set |url| to |global|'s <a>associated Document</a>'s {{Document/URL}}.
  1. If |global| is a {{WorkerGlobalScope}}, set |url| to |global|'s <a for=WorkerGlobalScope>URL</a>.
  1. <a>Assert</a>: |url| is a <a for=/>URL</a>.
  1. Let |documentURL| be the result of <a>strip URL for use in reports</a> on |url|.
  1. Let |blockedURL| be the result of <a>strip URL for use in reports</a> on |request|'s <a for=request>URL</a>.
  1. If |block| is true, <a for=list>for each</a> |endpoint| in |policy|'s <a>endpoints</a>:
     1. Let |body| be a new {{IntegrityViolationReportBody}}, initialized as follows:
                 :   {{IntegrityViolationReportBody/documentURL}}
                 ::  |documentURL|
                 :   {{IntegrityViolationReportBody/blockedURL}}
                 ::  |blockedURL|
                 :   {{IntegrityViolationReportBody/destination}}
                 ::  |request|'s <a for=request>destination</a>
                 :   {{IntegrityViolationReportBody/reportOnly}}
                 ::  false
     2. <a>Generate and queue a report</a> with the following arguments:
              :   <a for="generate and queue a report"><i>context</i></a>
              ::  |settingsObject|
              :   <a for="generate and queue a report"><i>type</i></a>
              ::  "`integrity-violation`"
              :   <a for="generate and queue a report"><i>destination</i></a>
              ::  |endpoint|
              :   <a for="generate and queue a report"><i>data</i></a>
              ::  |body|
  1. If |reportBlock| is true, <a for=list>for each</a> |endpoint| in |reportPolicy|'s <a>endpoints</a>:
     1. Let |reportBody| be a new {{IntegrityViolationReportBody}}, initialized as follows:
                 :   {{IntegrityViolationReportBody/documentURL}}
                 ::  |documentURL|
                 :   {{IntegrityViolationReportBody/blockedURL}}
                 ::  |blockedURL|
                 :   {{IntegrityViolationReportBody/destination}}
                 ::  |request|'s <a for=request>destination</a>
                 :   {{IntegrityViolationReportBody/reportOnly}}
                 ::  true 
     2. <a>Generate and queue a report</a> with the following arguments:
              :   <a for="generate and queue a report"><i>context</i></a>
              ::  |settingsObject|
              :   <a for="generate and queue a report"><i>type</i></a>
              ::  "`integrity-violation`"
              :   <a for="generate and queue a report"><i>destination</i></a>
              ::  |endpoint|
              :   <a for="generate and queue a report"><i>data</i></a>
              ::  |reportBody|

  # Proxies # {#proxies}

  Optimizing proxies and other intermediate servers which modify the
  responses MUST ensure that the digest associated
  with those responses stays in sync with the new content. One option
  is to ensure that the <a>integrity metadata</a> associated with
  resources is updated. Another
  would be simply to deliver only the canonical version of resources
  for which a page author has requested integrity verification.

  To help inform intermediate servers, those serving the resources SHOULD
  send along with the resource a <a>`Cache-Control`</a> header
  with a value of <a>`no-transform`</a>.

  <!-- ####################################################################### -->

  # Security and Privacy Considerations # {#security-considerations}

  <em> This section is not normative.</em>

  ## Non-secure contexts remain non-secure ## {#non-secure-contexts}

  <a>Integrity metadata</a> delivered by a context that is not a <a>Secure
  Context</a> such as an HTTP page, only protects an origin against a compromise
  of the server where an external resources is hosted. Network attackers can alter
  the digest in-flight (or remove it entirely, or do absolutely anything else to
  the document), just as they could alter the response the hash is meant to
  validate.  Thus, it is recommended that authors deliver integrity metadata only
  to a <a>Secure Context</a>. See also  <a
  href="http://www.w3.org/2001/tag/doc/web-https ">Securing the Web</a>.

  ## Hash collision attacks ## {#hash-collision-attacks}

  Digests are only as strong as the hash function used to generate them. It is
  recommended that user agents refuse to support known-weak hashing functions and
  limit supported algorithms to those known to be collision resistant. Examples of
  hashing functions that are not recommended include MD5 and SHA-1. At the time of
  writing, SHA-384 is a good baseline.

  Moreover, it is recommended that user agents re-evaluate their supported hash
  functions on a regular basis and deprecate support for those functions shown to
  be insecure. Over time, hash functions may be shown to be much weaker than
  expected and, in some cases, broken, so it is important that user agents stay
  aware of these developments.

  ## Cross-origin data leakage ## {#cross-origin-data-leakage}

  This specification requires integrity-protected cross-origin requests to use the
  <a>CORS protocol</a> to ensure that the resource's content is explicitly shared
  with the requestor. If that requirement were omitted,
  attackers could violate the <a
  href="http://www.w3.org/Security/wiki/Same_Origin_Policy">same-origin policy</a>
  and determine whether a cross-origin resource has certain content.

  Attackers would attempt to load the resource with a known digest, and
  watch for load failures. If the load fails, the attacker could surmise
  that the response didn't match the hash and thereby gain some insight into
  its contents. This might reveal, for example, whether or not a user is
  logged into a particular service.

  Moreover, attackers could brute-force specific values in an otherwise
  static resource. Consider a JSON response that looks like this:

  <div class="example">
  <xmp highlight="json">
      {"status": "authenticated", "username": "admin"}
  </xmp>
  </div>

  An attacker could precompute hashes for the response with a variety of
  common usernames, and specify those hashes while repeatedly attempting
  to load the document. A successful load would confirm that the attacker
  has correctly guessed the username.

  <!-- ####################################################################### -->

  # Acknowledgements # {#acknowledgements}

  Much of the content here is inspired heavily by Gervase Markham's <a
  href="http://www.gerv.net/security/link-fingerprints/">Link Fingerprints</a>
  concept as well as WHATWG's <a
  href="https://wiki.whatwg.org/wiki/Link_Hashes">Link Hashes</a>.

  A special thanks to Mike West for his invaluable contributions to the initial
  version of this spec. Thanks to Brad Hill, Anne van Kesteren, Jonathan
  Kingston, Fatih Kilic, Mark Nottingham, Sergey Shekyan, Dan Veditz, Eduardo Vela,
  Tanvi Vyas, Yoav Weiss, and Michal Zalewski for providing invaluable feedback.
